from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, DateField, RadioField, FileField, \
    TextAreaField, SelectField, FloatField, IntegerField
from wtforms.validators import DataRequired, EqualTo, Email, ValidationError
from flask_wtf.file import FileRequired, FileAllowed
from webapp.models import User


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired()])
    user_type = SelectField('Identity', validators=[DataRequired()],
                            choices=[
                                (1, 'landlord'),  # 房东
                                (2, 'Tenant')], coerce=int)  # 租客
    accept_rules = BooleanField('I accept the site', validators=[DataRequired()])
    submit = SubmitField('Register')


class ChangePasswordForm(FlaskForm):
    password = PasswordField('Origin Password', validators=[DataRequired()])
    new_password1 = PasswordField('New Password', validators=[DataRequired()])
    new_password2 = PasswordField('Repeat New Password', validators=[DataRequired()])
    submit = SubmitField('Reset')


class MyProfileForm(FlaskForm):
    nickname = StringField('Your Nickname')
    phone = StringField('Phone Number')
    address = StringField('Your Address')
    city = StringField('Your City')
    email = StringField('Email')
    zip = StringField('Zip of Your Area')
    about = TextAreaField('Your Information')
    facebook = StringField('Facebook Account')
    twitter = StringField('Twitter Account')
    google = StringField('Google Account')
    linkedin = StringField('LinkedIn Account')
    submit = SubmitField('Save Information')


class CalculatorForm(FlaskForm):
    total_loans = StringField('Total Loans', validators=[DataRequired()])
    annualized_rate = SelectField('Annualized Rate', validators=[DataRequired()],
                                  choices=[
                                      (1, 'Annual interest rate 1%'),
                                      (1.5, 'Annual interest rate 1.5%'),
                                      (2, 'Annual interest rate 2%'),
                                      (2.5, 'Annual interest rate 2.5%'),
                                      (3, 'Annual interest rate 3%'),
                                      (3.5, 'Annual interest rate 3.5%'),
                                      (4, 'Annual interest rate 4%'),
                                      (4.5, 'Annual interest rate 4.5%'),
                                      (5, 'Annual interest rate 5%'),
                                      (5.5, 'Annual interest rate 5.5%'),
                                      (6, 'Annual interest rate 6%'),
                                      (6.5, 'Annual interest rate 6.5%'),
                                      (7, 'Annual interest rate 7%'),
                                      (7.5, 'Annual interest rate 7.5%'),
                                      (8, 'Annual interest rate 8%'),
                                      (8.5, 'Annual interest rate 8.5%'),
                                      (9, 'Annual interest rate 9%'),
                                      (9.5, 'Annual interest rate 9.5%'),
                                      (10, 'Annual interest rate 10%')], coerce=int)

    repayment_years = StringField('Repayment Years', validators=[DataRequired()])

    types = SelectField('Loan Type', validators=[DataRequired()], choices=[(1, 'Equal principal and interest'),
                                                                           (2, 'Equal principal')], coerce=int)
    # A = FloatField('Repayment Years', validators=[DataRequired()])
    submit = SubmitField('Start the Calculation')


class AddHouseForm(FlaskForm):
    housename = StringField('House Detail', validators=[DataRequired()])
    size = StringField('House Size', validators=[DataRequired()])
    floorkind = SelectField('Floor Kind', validators=[DataRequired()],
                            choices=[(1, 'basement'), (2, 'low floor'), (3, 'medium floor'), (4, 'high floor')],
                            coerce=int)
    floornumber = StringField('Floor Number', validators=[DataRequired()])
    roomnumber = StringField('Room Number', validators=[DataRequired()])
    livingnumber = StringField('Living Room Number', validators=[DataRequired()])
    bathnumber = StringField('Bath Room Number', validators=[DataRequired()])
    renttype = SelectField('Rent Type', validators=[DataRequired()],
                           choices=[(1, 'whole rent'), (2, 'sharing rent')],
                           coerce=int)
    districtid = SelectField('District', validators=[DataRequired()],
                             # choices=[(1, '昌平'), (2, '朝阳'), (3, '大兴'), (4, '东城'), (5, '房山'), (6, '丰台'), (7, '海淀'),
                             #          (8, '怀柔'),
                             #          (9, '门头沟'), (10, '密云'), (11, '平谷'), (12, '石景山'), (13, '顺义'), (14, '通州'),
                             #          (15, '西城'), (16, '延庆'), (17, '亦庄开发区')],
                             choices=[(1, 'ChangPing'), (2, 'ChaoYang'), (3, 'DaXing'), (4, 'DongCheng'),
                                      (5, 'FangShan'), (6, 'FengTai'), (7, 'HaiDian'),
                                      (8, 'HuaiRou'),
                                      (9, 'MenTouGou'), (10, 'MiYun'), (11, 'PingGu'), (12, 'ShiJingShan'),
                                      (13, 'ShunYi'), (14, 'TongZhou'),
                                      (15, 'XiCheng'), (16, 'YanQing'), (17, 'YiZhuangKaiFaqu')],
                             coerce=int)
    communityid = SelectField('Community', validators=[DataRequired()],
                              # choices=[(1, '西关环岛'), (2, '北七家'), (3, '霍营'), (4, '鼓楼大街'), (5, '回龙观'), (6, '西三旗'),
                              #          (7, '东关'), (8, '天通苑'),
                              #          (9, '沙河'), (10, '南邵'), (11, '昌平其它'), (12, '小汤山'), (13, '立水桥'), (14, '奥林匹克公园'),
                              #          (15, '南口'),
                              #          (16, '安宁庄'), (17, '定福庄'), (18, '亚运村小营'), (19, '豆各庄'), (20, '双桥'), (21, '常营'),
                              #          (22, '首都机场'),
                              #          (23, '管庄'), (24, '十里河'), (25, '芍药居'), (26, '垡头'), (27, '和平里'), (28, '亚运村'),
                              #          (29, '红庙'),
                              #          (30, '石佛营'), (31, '朝阳其它'), (32, '国展'), (33, '东坝'), (34, '工体'), (35, '潘家园'),
                              #          (36, '三元桥'), (37, '北苑'),
                              #          (38, '华威桥'), (39, '十里堡'), (40, 'CBD'), (41, '惠新西街'), (42, '十八里店'), (43, '酒仙桥'),
                              #          (44, '劲松'),
                              #          (45, '百子湾'), (46, '方庄'), (47, '朝青'), (48, '望京'), (49, '欢乐谷'), (50, '中央别墅区'),
                              #          (51, '甘露园'), (52, '四惠'),
                              #          (53, '北工大'), (54, '成寿寺'), (55, '高碑店'), (56, '大望路'), (57, '太阳宫'), (58, '双井'),
                              #          (59, '团结湖'), (60, '南沙滩'),
                              #          (61, '东大桥'), (62, '甜水园'), (63, '西坝河'), (64, '健翔桥'), (65, '三里屯'), (66, '安贞'),
                              #          (67, '亮马桥'), (68, '未知'),
                              #          (69, '大山子'), (70, '建国门外'), (71, '朝阳门外'), (72, '东直门'), (73, '农展馆'), (74, '朝阳公园'),
                              #          (75, '马甸'),
                              #          (76, '燕莎'), (77, '安定门'), (78, '南中轴机场商务区'), (79, '高米店'), (80, '黄村火车站'),
                              #          (81, '枣园'), (82, '黄村中'),
                              #          (83, '西红门'), (84, '大兴其它'), (85, '瀛海'), (86, '天宫院'), (87, '义和庄'), (88, '大兴新机场'),
                              #          (89, '科技园区'),
                              #          (90, '旧宫'), (91, '观音寺'), (92, '亦庄'), (93, '亦庄开发区其它'), (94, '和义'),
                              #          (95, '大兴新机场洋房别墅区'),
                              #          (96, '天宫院南'), (97, '永定门'), (98, '崇文门'), (99, '东花市'), (100, '广渠门'), (101, '陶然亭'),
                              #          (102, '左安门'),
                              #          (103, '东四'), (104, '建国门内'), (105, '天坛'), (106, '前门'), (107, '地安门'), (108, '灯市口'),
                              #          (109, '金宝街'),
                              #          (110, '交道口'), (111, '朝阳门内'), (112, '蒲黄榆'), (113, '东单'), (114, '长阳'), (115, '良乡'),
                              #          (116, '阎村'),
                              #          (117, '城关'), (118, '燕山'), (119, '房山其它'), (120, '窦店'), (121, '青塔'), (122, '新宫'),
                              #          (123, '木樨园'),
                              #          (124, '花乡'), (125, '马家堡'), (126, '西罗园'), (127, '卢沟桥'), (128, '北大地'),
                              #          (129, '大红门'), (130, '看丹桥'),
                              #          (131, '洋桥'), (132, '玉泉营'), (133, '刘家窑'), (134, '五里店'), (135, '赵公口'),
                              #          (136, '宋家庄'), (137, '右安门外'),
                              #          (138, '角门'), (139, '六里桥'), (140, '七里庄'), (141, '丰台其它'), (142, '丽泽'), (143, '草桥'),
                              #          (144, '北京南站'),
                              #          (145, '太平桥'), (146, '菜户营'), (147, '马连道'), (148, '岳各庄'), (149, '五棵松'),
                              #          (150, '广安门'), (151, '马连洼'),
                              #          (152, '西山'), (153, '定慧寺'), (154, '海淀北部新区'), (155, '军博'), (156, '上地'),
                              #          (157, '清河'), (158, '厂洼'),
                              #          (159, '紫竹桥'), (160, '甘家口'), (161, '公主坟'), (162, '玉泉路'), (163, '田村'),
                              #          (164, '小西天'), (165, '万寿路'),
                              #          (166, '西直门'), (167, '二里庄'), (168, '皂君庙'), (169, '双榆树'), (170, '四季青'),
                              #          (171, '新街口'), (172, '苏州桥'),
                              #          (173, '颐和园'), (174, '知春路'), (175, '五道口'), (176, '圆明园'), (177, '牡丹园'),
                              #          (178, '西北旺'), (179, '学院路'),
                              #          (180, '万柳'), (181, '中关村'), (182, '西二旗'), (183, '杨庄'), (184, '魏公村'), (185, '世纪城'),
                              #          (186, '白石桥'),
                              #          (187, '北太平庄'), (188, '海淀其它'), (189, '怀柔'), (190, '大峪'), (191, '石门营'),
                              #          (192, '城子'), (193, '滨河西区'),
                              #          (194, '冯村'), (195, '门头沟其它'), (196, '密云其它'), (197, '平谷其它'), (198, '鲁谷'),
                              #          (199, '八角'), (200, '苹果园'),
                              #          (201, '石景山其它'), (202, '古城'), (203, '老山'), (204, '马坡'), (205, '顺义其它'),
                              #          (206, '顺义城'), (207, '后沙峪'),
                              #          (208, '天竺'), (209, '李桥'), (210, '乔庄'), (211, '北关'), (212, '万达'), (213, '临河里'),
                              #          (214, '武夷花园'),
                              #          (215, '果园'), (216, '玉桥'), (217, '梨园'), (218, '九棵树(家乐福)'), (219, '潞苑'),
                              #          (220, '通州北苑'), (221, '通州其它'),
                              #          (222, '马驹桥'), (223, '金融街'), (224, '牛街'), (225, '右安门内'), (226, '木樨地'),
                              #          (227, '西单'), (228, '长椿街'), (229, '月坛'),
                              #          (230, '车公庄'), (231, '阜成门'), (232, '天宁寺'), (233, '宣武门'), (234, '官园'),
                              #          (235, '白纸坊'), (236, '六铺炕'), (237, '德胜门'),
                              #          (238, '西四'), (239, '延庆其它')],
                              choices=[(1, 'XiGuanHuanDao'), (2, 'BeiQiJia'), (3, 'HuoYing'), (4, 'GuLouDaJie'),
                                       (5, 'HuiLongGuan'), (6, 'XiSanQi'),
                                       (7, 'DongGuan'), (8, 'TianTongYuan'),
                                       (9, 'ShaHe'), (10, 'NanShao'), (11, 'ChangPing Other'), (12, 'XiaoTangShan'),
                                       (13, 'LiShuiQiao'), (14, 'AoLinPiKeGongYuan'),
                                       (15, 'NanKou'),
                                       (16, 'AnNingZhuang'), (17, 'DingFuZhuang'), (18, 'YaYunCunXiaoYing'),
                                       (19, 'DouGeZhuang'), (20, 'ShuangQiao'), (21, 'ChangYing'),
                                       (22, 'ShouDuJiChang'),
                                       (23, 'GuanZhuang'), (24, 'ShiLiHe'), (25, 'ShaoYaoJu'), (26, 'FaTou'),
                                       (27, 'HePingLi'), (28, 'YaYunCun'),
                                       (29, 'HongMiao'),
                                       (30, 'ShiFoYing'), (31, 'ChaoYang Other'), (32, 'GuoZhan'), (33, 'DongBa'),
                                       (34, 'GongTi'), (35, 'PanJiaYuan'),
                                       (36, 'SanYuanQiao'), (37, 'BeiYuan'),
                                       (38, 'HuaWeiQiao'), (39, 'ShiLiBao'), (40, 'CBD'), (41, 'HuiXinXiJie'),
                                       (42, 'ShiBaLiDian'), (43, 'JiuXianQiao'),
                                       (44, 'JinSong'),
                                       (45, 'BaiZiWan'), (46, 'FangZhuang'), (47, 'ChaoQin'), (48, 'WangJing'),
                                       (49, 'HuanLeGu'), (50, 'ZhongYangBieShuQu'),
                                       (51, 'GanLuYuan'), (52, 'SiHui'),
                                       (53, 'BeiGongDa'), (54, 'ChengShouSi'), (55, 'GaoBeiDian'), (56, 'DaWangLu'),
                                       (57, 'TaiYangGong'), (58, 'ShuangJing'),
                                       (59, 'TuanJieHu'), (60, 'NanShaTan'),
                                       (61, 'DongDaQiao'), (62, 'TianShuiYuan'), (63, 'XiBaHe'), (64, 'JianXiangQiao'),
                                       (65, 'SanLiTun'), (66, 'AnZhen'),
                                       (67, 'LiangMaQiao'), (68, 'WeiZhi'),
                                       (69, 'DaShanZi'), (70, 'JianGuoMenWai'), (71, 'ChaoYangMenWai'),
                                       (72, 'DongZhiMen'), (73, 'NongZhanGuan'), (74, 'ChaoYangGongYuan'),
                                       (75, 'MaDian'),
                                       (76, 'YanSha'), (77, 'AnDingMen'), (78, 'NanZhongZhouJiChangShangWuQu'),
                                       (79, 'GaoMiDian'), (80, 'HuangCunHuoCheZhan'),
                                       (81, 'ZaoYuan'), (82, 'HuangCunZhong'),
                                       (83, 'XiHongMen'), (84, 'DaXing Other'), (85, 'YingHai'), (86, 'TianGongYuan'),
                                       (87, 'YiHeZhuang'), (88, 'DaXingXinJiChang'),
                                       (89, 'KeJiYuanQu'),
                                       (90, 'JiuGong'), (91, 'GuanYinSi'), (92, 'YiZhuang'),
                                       (93, 'YiZhuangKaiFaQu Other'), (94, 'HeYi'),
                                       (95, 'DaXingXinJiChangYangFangBieShuQu'),
                                       (96, 'TianGongYuanNan'), (97, 'YongDingMen'), (98, 'ChongWenMen'),
                                       (99, 'DongHuaShi'), (100, 'GuangQuMen'), (101, 'TaoRanTing'),
                                       (102, 'ZuoAnMen'),
                                       (103, 'DongSi'), (104, 'JianGuoMenNei'), (105, 'TianTan'), (106, 'QianMen'),
                                       (107, 'DiAnMen'), (108, 'DengShiKou'),
                                       (109, 'JinBaoJie'),
                                       (110, 'JiaoDaoKou'), (111, 'ChaoYangMenNei'), (112, 'PuHuangYu'),
                                       (113, 'DongDan'), (114, 'ChangYang'), (115, 'LiangXiang'),
                                       (116, 'YanCun'),
                                       (117, 'ChengGuan'), (118, 'YanShan'), (119, 'FangShan Other'), (120, 'DouDian'),
                                       (121, 'QingTa'), (122, 'XinGong'),
                                       (123, 'MuXiYuan'),
                                       (124, 'HuaXiang'), (125, 'MaJiaBao'), (126, 'XiLuoYuan'), (127, 'LuGouQiao'),
                                       (128, 'BeiDaDi'),
                                       (129, 'DaHongMen'), (130, 'KanDanQiao'),
                                       (131, 'YangQiao'), (132, 'YuQuanYing'), (133, 'LiuJiaYao'), (134, 'WuLiDian'),
                                       (135, 'ZhaoGongKou'),
                                       (136, 'SongJiaZhuang'), (137, 'YouAnMenWai'),
                                       (138, 'JiaoMen'), (139, 'LiuLiQiao'), (140, 'QiLiZhuang'),
                                       (141, 'FengTai Other'), (142, 'LiZe'), (143, 'CaoQiao'),
                                       (144, 'BeiJingNanZhan'),
                                       (145, 'TaiPingQiao'), (146, 'CaiHuYing'), (147, 'MaLianDao'),
                                       (148, 'YueGeZhuang'), (149, 'WuKeSong'),
                                       (150, 'GuangAnMen'), (151, 'MaLianWa'),
                                       (152, 'XiShan'), (153, 'DingHuiSi'), (154, 'HaiDianBeiBuXinQu'), (155, 'JunBo'),
                                       (156, 'ShangDi'),
                                       (157, 'QingHe'), (158, 'ChangWa'),
                                       (159, 'ZiZhuQiao'), (160, 'GanJiaKou'), (161, 'GongZhuFen'), (162, 'YuQuanLu'),
                                       (163, 'TianCun'),
                                       (164, 'XiaoXiTian'), (165, 'WanShouLu'),
                                       (166, 'XiZhiMen'), (167, 'ErLiZhuang'), (168, 'ZaoJunMiao'),
                                       (169, 'ShuangYuShu'), (170, 'SiJiQing'),
                                       (171, 'XinJieKou'), (172, 'SuZhouQiao'),
                                       (173, 'YiHeYuan'), (174, 'ZhiChunLu'), (175, 'WuDaoKou'), (176, 'YuanMingYuan'),
                                       (177, 'MuDanYuan'),
                                       (178, 'XiBeiWang'), (179, 'XueYuanLu'),
                                       (180, 'WanLiu'), (181, 'ZhongGuanCun'), (182, 'XiErQi'), (183, 'YangZhuang'),
                                       (184, 'WeiGongCun'), (185, 'ShiJiCheng'),
                                       (186, 'BaiShiQiao'),
                                       (187, 'BeiTaiPingZhuang'), (188, 'HaiDian Other'), (189, 'HuaiRou'),
                                       (190, 'DaYu'), (191, 'ShiMenYing'),
                                       (192, 'ChengZi'), (193, 'BinHeXiQu'),
                                       (194, 'FengCun'), (195, 'MenTouGou Other'), (196, 'MiYun Other'),
                                       (197, 'PingGu Other'), (198, 'LuGu'),
                                       (199, 'BaJiao'), (200, 'PingGuoYuan'),
                                       (201, 'ShiJingShan Other'), (202, 'GuCheng'), (203, 'LaoShan'), (204, 'MaPo'),
                                       (205, 'ShunYi Other'),
                                       (206, 'ShunYiCheng'), (207, 'HouShaYu'),
                                       (208, 'TianZhu'), (209, 'LiQiao'), (210, 'QiaoZhuang'), (211, 'BeiGuan'),
                                       (212, 'WanDa'), (213, 'LinHeLi'),
                                       (214, 'WuYiHuanYuan'),
                                       (215, 'GuoYuan'), (216, 'YuQiao'), (217, 'LiYuan'), (218, 'JiuKeShu(JiaLeFu)'),
                                       (219, 'LuYuan'),
                                       (220, 'TongZhouBeiYuan'), (221, 'TongZhou Other'),
                                       (222, 'MaJuQiao'), (223, 'JinRongJie'), (224, 'NiuJie'), (225, 'YouAnMenNei'),
                                       (226, 'MuXiDi'),
                                       (227, 'XiDan'), (228, 'ChangChunJie'), (229, 'YueTan'),
                                       (230, 'CheGongZhuang'), (231, 'FuChengMen'), (232, 'TianNingSi'),
                                       (233, 'XuanWuMen'), (234, 'GuanYuan'),
                                       (235, 'BaiZhiFang'), (236, 'LiuPuKang'), (237, 'DeShengMen'),
                                       (238, 'XiSi'), (239, 'YanQing Other')],
                              coerce=int)
    price = StringField('Price', validators=[DataRequired()])
    description = TextAreaField('House Description', validators=[DataRequired()])
    imagename = FileField('Your House Photo(Only JPG and PNG)',
                          validators=[FileRequired(message=u'Only JPG and PNG files please'), FileAllowed(['jpg', 'png'] )])
    upload = SubmitField('Upload House')


class ChangeHouseForm(FlaskForm):
    housename = StringField('House Detail', validators=[DataRequired()])
    size = StringField('House Size', validators=[DataRequired()])
    floorkind = SelectField('Floor Kind', validators=[DataRequired()],
                            choices=[(1, 'basement'), (2, 'low floor'), (3, 'medium floor'), (4, 'high floor')],
                            coerce=int)
    floornumber = StringField('Floor Number', validators=[DataRequired()])
    roomnumber = StringField('Room Number', validators=[DataRequired()])
    livingnumber = StringField('Living Room Number', validators=[DataRequired()])
    bathnumber = StringField('Bath Room Number', validators=[DataRequired()])
    renttype = SelectField('Rent Type', validators=[DataRequired()],
                           choices=[(1, 'whole rent'), (2, 'sharing rent')],
                           coerce=int)
    districtid = SelectField('District', validators=[DataRequired()],
                             # choices=[(1, '昌平'), (2, '朝阳'), (3, '大兴'), (4, '东城'), (5, '房山'), (6, '丰台'), (7, '海淀'),
                             #          (8, '怀柔'),
                             #          (9, '门头沟'), (10, '密云'), (11, '平谷'), (12, '石景山'), (13, '顺义'), (14, '通州'),
                             #          (15, '西城'), (16, '延庆'), (17, '亦庄开发区')],
                             choices=[(1, 'ChangPing'), (2, 'ChaoYang'), (3, 'DaXing'), (4, 'DongCheng'),
                                      (5, 'FangShan'), (6, 'FengTai'), (7, 'HaiDian'),
                                      (8, 'HuaiRou'),
                                      (9, 'MenTouGou'), (10, 'MiYun'), (11, 'PingGu'), (12, 'ShiJingShan'),
                                      (13, 'ShunYi'), (14, 'TongZhou'),
                                      (15, 'XiCheng'), (16, 'YanQing'), (17, 'YiZhuangKaiFaqu')],
                             coerce=int)
    communityid = SelectField('Community', validators=[DataRequired()],
                              # choices=[(1, '西关环岛'), (2, '北七家'), (3, '霍营'), (4, '鼓楼大街'), (5, '回龙观'), (6, '西三旗'),
                              #          (7, '东关'), (8, '天通苑'),
                              #          (9, '沙河'), (10, '南邵'), (11, '昌平其它'), (12, '小汤山'), (13, '立水桥'), (14, '奥林匹克公园'),
                              #          (15, '南口'),
                              #          (16, '安宁庄'), (17, '定福庄'), (18, '亚运村小营'), (19, '豆各庄'), (20, '双桥'), (21, '常营'),
                              #          (22, '首都机场'),
                              #          (23, '管庄'), (24, '十里河'), (25, '芍药居'), (26, '垡头'), (27, '和平里'), (28, '亚运村'),
                              #          (29, '红庙'),
                              #          (30, '石佛营'), (31, '朝阳其它'), (32, '国展'), (33, '东坝'), (34, '工体'), (35, '潘家园'),
                              #          (36, '三元桥'), (37, '北苑'),
                              #          (38, '华威桥'), (39, '十里堡'), (40, 'CBD'), (41, '惠新西街'), (42, '十八里店'), (43, '酒仙桥'),
                              #          (44, '劲松'),
                              #          (45, '百子湾'), (46, '方庄'), (47, '朝青'), (48, '望京'), (49, '欢乐谷'), (50, '中央别墅区'),
                              #          (51, '甘露园'), (52, '四惠'),
                              #          (53, '北工大'), (54, '成寿寺'), (55, '高碑店'), (56, '大望路'), (57, '太阳宫'), (58, '双井'),
                              #          (59, '团结湖'), (60, '南沙滩'),
                              #          (61, '东大桥'), (62, '甜水园'), (63, '西坝河'), (64, '健翔桥'), (65, '三里屯'), (66, '安贞'),
                              #          (67, '亮马桥'), (68, '未知'),
                              #          (69, '大山子'), (70, '建国门外'), (71, '朝阳门外'), (72, '东直门'), (73, '农展馆'), (74, '朝阳公园'),
                              #          (75, '马甸'),
                              #          (76, '燕莎'), (77, '安定门'), (78, '南中轴机场商务区'), (79, '高米店'), (80, '黄村火车站'),
                              #          (81, '枣园'), (82, '黄村中'),
                              #          (83, '西红门'), (84, '大兴其它'), (85, '瀛海'), (86, '天宫院'), (87, '义和庄'), (88, '大兴新机场'),
                              #          (89, '科技园区'),
                              #          (90, '旧宫'), (91, '观音寺'), (92, '亦庄'), (93, '亦庄开发区其它'), (94, '和义'),
                              #          (95, '大兴新机场洋房别墅区'),
                              #          (96, '天宫院南'), (97, '永定门'), (98, '崇文门'), (99, '东花市'), (100, '广渠门'), (101, '陶然亭'),
                              #          (102, '左安门'),
                              #          (103, '东四'), (104, '建国门内'), (105, '天坛'), (106, '前门'), (107, '地安门'), (108, '灯市口'),
                              #          (109, '金宝街'),
                              #          (110, '交道口'), (111, '朝阳门内'), (112, '蒲黄榆'), (113, '东单'), (114, '长阳'), (115, '良乡'),
                              #          (116, '阎村'),
                              #          (117, '城关'), (118, '燕山'), (119, '房山其它'), (120, '窦店'), (121, '青塔'), (122, '新宫'),
                              #          (123, '木樨园'),
                              #          (124, '花乡'), (125, '马家堡'), (126, '西罗园'), (127, '卢沟桥'), (128, '北大地'),
                              #          (129, '大红门'), (130, '看丹桥'),
                              #          (131, '洋桥'), (132, '玉泉营'), (133, '刘家窑'), (134, '五里店'), (135, '赵公口'),
                              #          (136, '宋家庄'), (137, '右安门外'),
                              #          (138, '角门'), (139, '六里桥'), (140, '七里庄'), (141, '丰台其它'), (142, '丽泽'), (143, '草桥'),
                              #          (144, '北京南站'),
                              #          (145, '太平桥'), (146, '菜户营'), (147, '马连道'), (148, '岳各庄'), (149, '五棵松'),
                              #          (150, '广安门'), (151, '马连洼'),
                              #          (152, '西山'), (153, '定慧寺'), (154, '海淀北部新区'), (155, '军博'), (156, '上地'),
                              #          (157, '清河'), (158, '厂洼'),
                              #          (159, '紫竹桥'), (160, '甘家口'), (161, '公主坟'), (162, '玉泉路'), (163, '田村'),
                              #          (164, '小西天'), (165, '万寿路'),
                              #          (166, '西直门'), (167, '二里庄'), (168, '皂君庙'), (169, '双榆树'), (170, '四季青'),
                              #          (171, '新街口'), (172, '苏州桥'),
                              #          (173, '颐和园'), (174, '知春路'), (175, '五道口'), (176, '圆明园'), (177, '牡丹园'),
                              #          (178, '西北旺'), (179, '学院路'),
                              #          (180, '万柳'), (181, '中关村'), (182, '西二旗'), (183, '杨庄'), (184, '魏公村'), (185, '世纪城'),
                              #          (186, '白石桥'),
                              #          (187, '北太平庄'), (188, '海淀其它'), (189, '怀柔'), (190, '大峪'), (191, '石门营'),
                              #          (192, '城子'), (193, '滨河西区'),
                              #          (194, '冯村'), (195, '门头沟其它'), (196, '密云其它'), (197, '平谷其它'), (198, '鲁谷'),
                              #          (199, '八角'), (200, '苹果园'),
                              #          (201, '石景山其它'), (202, '古城'), (203, '老山'), (204, '马坡'), (205, '顺义其它'),
                              #          (206, '顺义城'), (207, '后沙峪'),
                              #          (208, '天竺'), (209, '李桥'), (210, '乔庄'), (211, '北关'), (212, '万达'), (213, '临河里'),
                              #          (214, '武夷花园'),
                              #          (215, '果园'), (216, '玉桥'), (217, '梨园'), (218, '九棵树(家乐福)'), (219, '潞苑'),
                              #          (220, '通州北苑'), (221, '通州其它'),
                              #          (222, '马驹桥'), (223, '金融街'), (224, '牛街'), (225, '右安门内'), (226, '木樨地'),
                              #          (227, '西单'), (228, '长椿街'), (229, '月坛'),
                              #          (230, '车公庄'), (231, '阜成门'), (232, '天宁寺'), (233, '宣武门'), (234, '官园'),
                              #          (235, '白纸坊'), (236, '六铺炕'), (237, '德胜门'),
                              #          (238, '西四'), (239, '延庆其它')],
                              choices=[(1, 'XiGuanHuanDao'), (2, 'BeiQiJia'), (3, 'HuoYing'), (4, 'GuLouDaJie'),
                                       (5, 'HuiLongGuan'), (6, 'XiSanQi'),
                                       (7, 'DongGuan'), (8, 'TianTongYuan'),
                                       (9, 'ShaHe'), (10, 'NanShao'), (11, 'ChangPing Other'), (12, 'XiaoTangShan'),
                                       (13, 'LiShuiQiao'), (14, 'AoLinPiKeGongYuan'),
                                       (15, 'NanKou'),
                                       (16, 'AnNingZhuang'), (17, 'DingFuZhuang'), (18, 'YaYunCunXiaoYing'),
                                       (19, 'DouGeZhuang'), (20, 'ShuangQiao'), (21, 'ChangYing'),
                                       (22, 'ShouDuJiChang'),
                                       (23, 'GuanZhuang'), (24, 'ShiLiHe'), (25, 'ShaoYaoJu'), (26, 'FaTou'),
                                       (27, 'HePingLi'), (28, 'YaYunCun'),
                                       (29, 'HongMiao'),
                                       (30, 'ShiFoYing'), (31, 'ChaoYang Other'), (32, 'GuoZhan'), (33, 'DongBa'),
                                       (34, 'GongTi'), (35, 'PanJiaYuan'),
                                       (36, 'SanYuanQiao'), (37, 'BeiYuan'),
                                       (38, 'HuaWeiQiao'), (39, 'ShiLiBao'), (40, 'CBD'), (41, 'HuiXinXiJie'),
                                       (42, 'ShiBaLiDian'), (43, 'JiuXianQiao'),
                                       (44, 'JinSong'),
                                       (45, 'BaiZiWan'), (46, 'FangZhuang'), (47, 'ChaoQin'), (48, 'WangJing'),
                                       (49, 'HuanLeGu'), (50, 'ZhongYangBieShuQu'),
                                       (51, 'GanLuYuan'), (52, 'SiHui'),
                                       (53, 'BeiGongDa'), (54, 'ChengShouSi'), (55, 'GaoBeiDian'), (56, 'DaWangLu'),
                                       (57, 'TaiYangGong'), (58, 'ShuangJing'),
                                       (59, 'TuanJieHu'), (60, 'NanShaTan'),
                                       (61, 'DongDaQiao'), (62, 'TianShuiYuan'), (63, 'XiBaHe'), (64, 'JianXiangQiao'),
                                       (65, 'SanLiTun'), (66, 'AnZhen'),
                                       (67, 'LiangMaQiao'), (68, 'WeiZhi'),
                                       (69, 'DaShanZi'), (70, 'JianGuoMenWai'), (71, 'ChaoYangMenWai'),
                                       (72, 'DongZhiMen'), (73, 'NongZhanGuan'), (74, 'ChaoYangGongYuan'),
                                       (75, 'MaDian'),
                                       (76, 'YanSha'), (77, 'AnDingMen'), (78, 'NanZhongZhouJiChangShangWuQu'),
                                       (79, 'GaoMiDian'), (80, 'HuangCunHuoCheZhan'),
                                       (81, 'ZaoYuan'), (82, 'HuangCunZhong'),
                                       (83, 'XiHongMen'), (84, 'DaXing Other'), (85, 'YingHai'), (86, 'TianGongYuan'),
                                       (87, 'YiHeZhuang'), (88, 'DaXingXinJiChang'),
                                       (89, 'KeJiYuanQu'),
                                       (90, 'JiuGong'), (91, 'GuanYinSi'), (92, 'YiZhuang'),
                                       (93, 'YiZhuangKaiFaQu Other'), (94, 'HeYi'),
                                       (95, 'DaXingXinJiChangYangFangBieShuQu'),
                                       (96, 'TianGongYuanNan'), (97, 'YongDingMen'), (98, 'ChongWenMen'),
                                       (99, 'DongHuaShi'), (100, 'GuangQuMen'), (101, 'TaoRanTing'),
                                       (102, 'ZuoAnMen'),
                                       (103, 'DongSi'), (104, 'JianGuoMenNei'), (105, 'TianTan'), (106, 'QianMen'),
                                       (107, 'DiAnMen'), (108, 'DengShiKou'),
                                       (109, 'JinBaoJie'),
                                       (110, 'JiaoDaoKou'), (111, 'ChaoYangMenNei'), (112, 'PuHuangYu'),
                                       (113, 'DongDan'), (114, 'ChangYang'), (115, 'LiangXiang'),
                                       (116, 'YanCun'),
                                       (117, 'ChengGuan'), (118, 'YanShan'), (119, 'FangShan Other'), (120, 'DouDian'),
                                       (121, 'QingTa'), (122, 'XinGong'),
                                       (123, 'MuXiYuan'),
                                       (124, 'HuaXiang'), (125, 'MaJiaBao'), (126, 'XiLuoYuan'), (127, 'LuGouQiao'),
                                       (128, 'BeiDaDi'),
                                       (129, 'DaHongMen'), (130, 'KanDanQiao'),
                                       (131, 'YangQiao'), (132, 'YuQuanYing'), (133, 'LiuJiaYao'), (134, 'WuLiDian'),
                                       (135, 'ZhaoGongKou'),
                                       (136, 'SongJiaZhuang'), (137, 'YouAnMenWai'),
                                       (138, 'JiaoMen'), (139, 'LiuLiQiao'), (140, 'QiLiZhuang'),
                                       (141, 'FengTai Other'), (142, 'LiZe'), (143, 'CaoQiao'),
                                       (144, 'BeiJingNanZhan'),
                                       (145, 'TaiPingQiao'), (146, 'CaiHuYing'), (147, 'MaLianDao'),
                                       (148, 'YueGeZhuang'), (149, 'WuKeSong'),
                                       (150, 'GuangAnMen'), (151, 'MaLianWa'),
                                       (152, 'XiShan'), (153, 'DingHuiSi'), (154, 'HaiDianBeiBuXinQu'), (155, 'JunBo'),
                                       (156, 'ShangDi'),
                                       (157, 'QingHe'), (158, 'ChangWa'),
                                       (159, 'ZiZhuQiao'), (160, 'GanJiaKou'), (161, 'GongZhuFen'), (162, 'YuQuanLu'),
                                       (163, 'TianCun'),
                                       (164, 'XiaoXiTian'), (165, 'WanShouLu'),
                                       (166, 'XiZhiMen'), (167, 'ErLiZhuang'), (168, 'ZaoJunMiao'),
                                       (169, 'ShuangYuShu'), (170, 'SiJiQing'),
                                       (171, 'XinJieKou'), (172, 'SuZhouQiao'),
                                       (173, 'YiHeYuan'), (174, 'ZhiChunLu'), (175, 'WuDaoKou'), (176, 'YuanMingYuan'),
                                       (177, 'MuDanYuan'),
                                       (178, 'XiBeiWang'), (179, 'XueYuanLu'),
                                       (180, 'WanLiu'), (181, 'ZhongGuanCun'), (182, 'XiErQi'), (183, 'YangZhuang'),
                                       (184, 'WeiGongCun'), (185, 'ShiJiCheng'),
                                       (186, 'BaiShiQiao'),
                                       (187, 'BeiTaiPingZhuang'), (188, 'HaiDian Other'), (189, 'HuaiRou'),
                                       (190, 'DaYu'), (191, 'ShiMenYing'),
                                       (192, 'ChengZi'), (193, 'BinHeXiQu'),
                                       (194, 'FengCun'), (195, 'MenTouGou Other'), (196, 'MiYun Other'),
                                       (197, 'PingGu Other'), (198, 'LuGu'),
                                       (199, 'BaJiao'), (200, 'PingGuoYuan'),
                                       (201, 'ShiJingShan Other'), (202, 'GuCheng'), (203, 'LaoShan'), (204, 'MaPo'),
                                       (205, 'ShunYi Other'),
                                       (206, 'ShunYiCheng'), (207, 'HouShaYu'),
                                       (208, 'TianZhu'), (209, 'LiQiao'), (210, 'QiaoZhuang'), (211, 'BeiGuan'),
                                       (212, 'WanDa'), (213, 'LinHeLi'),
                                       (214, 'WuYiHuanYuan'),
                                       (215, 'GuoYuan'), (216, 'YuQiao'), (217, 'LiYuan'), (218, 'JiuKeShu(JiaLeFu)'),
                                       (219, 'LuYuan'),
                                       (220, 'TongZhouBeiYuan'), (221, 'TongZhou Other'),
                                       (222, 'MaJuQiao'), (223, 'JinRongJie'), (224, 'NiuJie'), (225, 'YouAnMenNei'),
                                       (226, 'MuXiDi'),
                                       (227, 'XiDan'), (228, 'ChangChunJie'), (229, 'YueTan'),
                                       (230, 'CheGongZhuang'), (231, 'FuChengMen'), (232, 'TianNingSi'),
                                       (233, 'XuanWuMen'), (234, 'GuanYuan'),
                                       (235, 'BaiZhiFang'), (236, 'LiuPuKang'), (237, 'DeShengMen'),
                                       (238, 'XiSi'), (239, 'YanQing Other')],
                              coerce=int)
    price = StringField('Price', validators=[DataRequired()])
    description = TextAreaField('House Description', validators=[DataRequired()])
    imagename = FileField('Your House Photo(Only JPG and PNG)',
                          validators=[FileAllowed(['jpg', 'png'], message=u'Only JPG and PNG files please')])
    change = SubmitField('Update Information')


class SearchForm(FlaskForm):
    floorkind = SelectField('Floor Kind', validators=[DataRequired()],
                            choices=[(1, 'basement'), (2, 'low floor'), (3, 'medium floor'), (4, 'high floor')],
                            coerce=int)
    renttype = SelectField('Rent Type', validators=[DataRequired()],
                           choices=[(1, 'whole rent'), (2, 'sharing rent')],
                           coerce=int)
    districtid = SelectField('District', validators=[DataRequired()],
                             # choices=[(1, '昌平'), (2, '朝阳'), (3, '大兴'), (4, '东城'), (5, '房山'), (6, '丰台'), (7, '海淀'),
                             #          (8, '怀柔'),
                             #          (9, '门头沟'), (10, '密云'), (11, '平谷'), (12, '石景山'), (13, '顺义'), (14, '通州'),
                             #          (15, '西城'), (16, '延庆'), (17, '亦庄开发区')],
                             choices=[(1, 'ChangPing'), (2, 'ChaoYang'), (3, 'DaXing'), (4, 'DongCheng'),
                                      (5, 'FangShan'), (6, 'FengTai'), (7, 'HaiDian'),
                                      (8, 'HuaiRou'),
                                      (9, 'MenTouGou'), (10, 'MiYun'), (11, 'PingGu'), (12, 'ShiJingShan'),
                                      (13, 'ShunYi'), (14, 'TongZhou'),
                                      (15, 'XiCheng'), (16, 'YanQing'), (17, 'YiZhuangKaiFaqu')],
                             coerce=int)
    communityid = SelectField('Community', validators=[DataRequired()],
                              # choices=[(1, '西关环岛'), (2, '北七家'), (3, '霍营'), (4, '鼓楼大街'), (5, '回龙观'), (6, '西三旗'),
                              #          (7, '东关'), (8, '天通苑'),
                              #          (9, '沙河'), (10, '南邵'), (11, '昌平其它'), (12, '小汤山'), (13, '立水桥'), (14, '奥林匹克公园'),
                              #          (15, '南口'),
                              #          (16, '安宁庄'), (17, '定福庄'), (18, '亚运村小营'), (19, '豆各庄'), (20, '双桥'), (21, '常营'),
                              #          (22, '首都机场'),
                              #          (23, '管庄'), (24, '十里河'), (25, '芍药居'), (26, '垡头'), (27, '和平里'), (28, '亚运村'),
                              #          (29, '红庙'),
                              #          (30, '石佛营'), (31, '朝阳其它'), (32, '国展'), (33, '东坝'), (34, '工体'), (35, '潘家园'),
                              #          (36, '三元桥'), (37, '北苑'),
                              #          (38, '华威桥'), (39, '十里堡'), (40, 'CBD'), (41, '惠新西街'), (42, '十八里店'), (43, '酒仙桥'),
                              #          (44, '劲松'),
                              #          (45, '百子湾'), (46, '方庄'), (47, '朝青'), (48, '望京'), (49, '欢乐谷'), (50, '中央别墅区'),
                              #          (51, '甘露园'), (52, '四惠'),
                              #          (53, '北工大'), (54, '成寿寺'), (55, '高碑店'), (56, '大望路'), (57, '太阳宫'), (58, '双井'),
                              #          (59, '团结湖'), (60, '南沙滩'),
                              #          (61, '东大桥'), (62, '甜水园'), (63, '西坝河'), (64, '健翔桥'), (65, '三里屯'), (66, '安贞'),
                              #          (67, '亮马桥'), (68, '未知'),
                              #          (69, '大山子'), (70, '建国门外'), (71, '朝阳门外'), (72, '东直门'), (73, '农展馆'), (74, '朝阳公园'),
                              #          (75, '马甸'),
                              #          (76, '燕莎'), (77, '安定门'), (78, '南中轴机场商务区'), (79, '高米店'), (80, '黄村火车站'),
                              #          (81, '枣园'), (82, '黄村中'),
                              #          (83, '西红门'), (84, '大兴其它'), (85, '瀛海'), (86, '天宫院'), (87, '义和庄'), (88, '大兴新机场'),
                              #          (89, '科技园区'),
                              #          (90, '旧宫'), (91, '观音寺'), (92, '亦庄'), (93, '亦庄开发区其它'), (94, '和义'),
                              #          (95, '大兴新机场洋房别墅区'),
                              #          (96, '天宫院南'), (97, '永定门'), (98, '崇文门'), (99, '东花市'), (100, '广渠门'), (101, '陶然亭'),
                              #          (102, '左安门'),
                              #          (103, '东四'), (104, '建国门内'), (105, '天坛'), (106, '前门'), (107, '地安门'), (108, '灯市口'),
                              #          (109, '金宝街'),
                              #          (110, '交道口'), (111, '朝阳门内'), (112, '蒲黄榆'), (113, '东单'), (114, '长阳'), (115, '良乡'),
                              #          (116, '阎村'),
                              #          (117, '城关'), (118, '燕山'), (119, '房山其它'), (120, '窦店'), (121, '青塔'), (122, '新宫'),
                              #          (123, '木樨园'),
                              #          (124, '花乡'), (125, '马家堡'), (126, '西罗园'), (127, '卢沟桥'), (128, '北大地'),
                              #          (129, '大红门'), (130, '看丹桥'),
                              #          (131, '洋桥'), (132, '玉泉营'), (133, '刘家窑'), (134, '五里店'), (135, '赵公口'),
                              #          (136, '宋家庄'), (137, '右安门外'),
                              #          (138, '角门'), (139, '六里桥'), (140, '七里庄'), (141, '丰台其它'), (142, '丽泽'), (143, '草桥'),
                              #          (144, '北京南站'),
                              #          (145, '太平桥'), (146, '菜户营'), (147, '马连道'), (148, '岳各庄'), (149, '五棵松'),
                              #          (150, '广安门'), (151, '马连洼'),
                              #          (152, '西山'), (153, '定慧寺'), (154, '海淀北部新区'), (155, '军博'), (156, '上地'),
                              #          (157, '清河'), (158, '厂洼'),
                              #          (159, '紫竹桥'), (160, '甘家口'), (161, '公主坟'), (162, '玉泉路'), (163, '田村'),
                              #          (164, '小西天'), (165, '万寿路'),
                              #          (166, '西直门'), (167, '二里庄'), (168, '皂君庙'), (169, '双榆树'), (170, '四季青'),
                              #          (171, '新街口'), (172, '苏州桥'),
                              #          (173, '颐和园'), (174, '知春路'), (175, '五道口'), (176, '圆明园'), (177, '牡丹园'),
                              #          (178, '西北旺'), (179, '学院路'),
                              #          (180, '万柳'), (181, '中关村'), (182, '西二旗'), (183, '杨庄'), (184, '魏公村'), (185, '世纪城'),
                              #          (186, '白石桥'),
                              #          (187, '北太平庄'), (188, '海淀其它'), (189, '怀柔'), (190, '大峪'), (191, '石门营'),
                              #          (192, '城子'), (193, '滨河西区'),
                              #          (194, '冯村'), (195, '门头沟其它'), (196, '密云其它'), (197, '平谷其它'), (198, '鲁谷'),
                              #          (199, '八角'), (200, '苹果园'),
                              #          (201, '石景山其它'), (202, '古城'), (203, '老山'), (204, '马坡'), (205, '顺义其它'),
                              #          (206, '顺义城'), (207, '后沙峪'),
                              #          (208, '天竺'), (209, '李桥'), (210, '乔庄'), (211, '北关'), (212, '万达'), (213, '临河里'),
                              #          (214, '武夷花园'),
                              #          (215, '果园'), (216, '玉桥'), (217, '梨园'), (218, '九棵树(家乐福)'), (219, '潞苑'),
                              #          (220, '通州北苑'), (221, '通州其它'),
                              #          (222, '马驹桥'), (223, '金融街'), (224, '牛街'), (225, '右安门内'), (226, '木樨地'),
                              #          (227, '西单'), (228, '长椿街'), (229, '月坛'),
                              #          (230, '车公庄'), (231, '阜成门'), (232, '天宁寺'), (233, '宣武门'), (234, '官园'),
                              #          (235, '白纸坊'), (236, '六铺炕'), (237, '德胜门'),
                              #          (238, '西四'), (239, '延庆其它')],
                              choices=[(1, 'XiGuanHuanDao'), (2, 'BeiQiJia'), (3, 'HuoYing'), (4, 'GuLouDaJie'),
                                       (5, 'HuiLongGuan'), (6, 'XiSanQi'),
                                       (7, 'DongGuan'), (8, 'TianTongYuan'),
                                       (9, 'ShaHe'), (10, 'NanShao'), (11, 'ChangPing Other'), (12, 'XiaoTangShan'),
                                       (13, 'LiShuiQiao'), (14, 'AoLinPiKeGongYuan'),
                                       (15, 'NanKou'),
                                       (16, 'AnNingZhuang'), (17, 'DingFuZhuang'), (18, 'YaYunCunXiaoYing'),
                                       (19, 'DouGeZhuang'), (20, 'ShuangQiao'), (21, 'ChangYing'),
                                       (22, 'ShouDuJiChang'),
                                       (23, 'GuanZhuang'), (24, 'ShiLiHe'), (25, 'ShaoYaoJu'), (26, 'FaTou'),
                                       (27, 'HePingLi'), (28, 'YaYunCun'),
                                       (29, 'HongMiao'),
                                       (30, 'ShiFoYing'), (31, 'ChaoYang Other'), (32, 'GuoZhan'), (33, 'DongBa'),
                                       (34, 'GongTi'), (35, 'PanJiaYuan'),
                                       (36, 'SanYuanQiao'), (37, 'BeiYuan'),
                                       (38, 'HuaWeiQiao'), (39, 'ShiLiBao'), (40, 'CBD'), (41, 'HuiXinXiJie'),
                                       (42, 'ShiBaLiDian'), (43, 'JiuXianQiao'),
                                       (44, 'JinSong'),
                                       (45, 'BaiZiWan'), (46, 'FangZhuang'), (47, 'ChaoQin'), (48, 'WangJing'),
                                       (49, 'HuanLeGu'), (50, 'ZhongYangBieShuQu'),
                                       (51, 'GanLuYuan'), (52, 'SiHui'),
                                       (53, 'BeiGongDa'), (54, 'ChengShouSi'), (55, 'GaoBeiDian'), (56, 'DaWangLu'),
                                       (57, 'TaiYangGong'), (58, 'ShuangJing'),
                                       (59, 'TuanJieHu'), (60, 'NanShaTan'),
                                       (61, 'DongDaQiao'), (62, 'TianShuiYuan'), (63, 'XiBaHe'), (64, 'JianXiangQiao'),
                                       (65, 'SanLiTun'), (66, 'AnZhen'),
                                       (67, 'LiangMaQiao'), (68, 'WeiZhi'),
                                       (69, 'DaShanZi'), (70, 'JianGuoMenWai'), (71, 'ChaoYangMenWai'),
                                       (72, 'DongZhiMen'), (73, 'NongZhanGuan'), (74, 'ChaoYangGongYuan'),
                                       (75, 'MaDian'),
                                       (76, 'YanSha'), (77, 'AnDingMen'), (78, 'NanZhongZhouJiChangShangWuQu'),
                                       (79, 'GaoMiDian'), (80, 'HuangCunHuoCheZhan'),
                                       (81, 'ZaoYuan'), (82, 'HuangCunZhong'),
                                       (83, 'XiHongMen'), (84, 'DaXing Other'), (85, 'YingHai'), (86, 'TianGongYuan'),
                                       (87, 'YiHeZhuang'), (88, 'DaXingXinJiChang'),
                                       (89, 'KeJiYuanQu'),
                                       (90, 'JiuGong'), (91, 'GuanYinSi'), (92, 'YiZhuang'),
                                       (93, 'YiZhuangKaiFaQu Other'), (94, 'HeYi'),
                                       (95, 'DaXingXinJiChangYangFangBieShuQu'),
                                       (96, 'TianGongYuanNan'), (97, 'YongDingMen'), (98, 'ChongWenMen'),
                                       (99, 'DongHuaShi'), (100, 'GuangQuMen'), (101, 'TaoRanTing'),
                                       (102, 'ZuoAnMen'),
                                       (103, 'DongSi'), (104, 'JianGuoMenNei'), (105, 'TianTan'), (106, 'QianMen'),
                                       (107, 'DiAnMen'), (108, 'DengShiKou'),
                                       (109, 'JinBaoJie'),
                                       (110, 'JiaoDaoKou'), (111, 'ChaoYangMenNei'), (112, 'PuHuangYu'),
                                       (113, 'DongDan'), (114, 'ChangYang'), (115, 'LiangXiang'),
                                       (116, 'YanCun'),
                                       (117, 'ChengGuan'), (118, 'YanShan'), (119, 'FangShan Other'), (120, 'DouDian'),
                                       (121, 'QingTa'), (122, 'XinGong'),
                                       (123, 'MuXiYuan'),
                                       (124, 'HuaXiang'), (125, 'MaJiaBao'), (126, 'XiLuoYuan'), (127, 'LuGouQiao'),
                                       (128, 'BeiDaDi'),
                                       (129, 'DaHongMen'), (130, 'KanDanQiao'),
                                       (131, 'YangQiao'), (132, 'YuQuanYing'), (133, 'LiuJiaYao'), (134, 'WuLiDian'),
                                       (135, 'ZhaoGongKou'),
                                       (136, 'SongJiaZhuang'), (137, 'YouAnMenWai'),
                                       (138, 'JiaoMen'), (139, 'LiuLiQiao'), (140, 'QiLiZhuang'),
                                       (141, 'FengTai Other'), (142, 'LiZe'), (143, 'CaoQiao'),
                                       (144, 'BeiJingNanZhan'),
                                       (145, 'TaiPingQiao'), (146, 'CaiHuYing'), (147, 'MaLianDao'),
                                       (148, 'YueGeZhuang'), (149, 'WuKeSong'),
                                       (150, 'GuangAnMen'), (151, 'MaLianWa'),
                                       (152, 'XiShan'), (153, 'DingHuiSi'), (154, 'HaiDianBeiBuXinQu'), (155, 'JunBo'),
                                       (156, 'ShangDi'),
                                       (157, 'QingHe'), (158, 'ChangWa'),
                                       (159, 'ZiZhuQiao'), (160, 'GanJiaKou'), (161, 'GongZhuFen'), (162, 'YuQuanLu'),
                                       (163, 'TianCun'),
                                       (164, 'XiaoXiTian'), (165, 'WanShouLu'),
                                       (166, 'XiZhiMen'), (167, 'ErLiZhuang'), (168, 'ZaoJunMiao'),
                                       (169, 'ShuangYuShu'), (170, 'SiJiQing'),
                                       (171, 'XinJieKou'), (172, 'SuZhouQiao'),
                                       (173, 'YiHeYuan'), (174, 'ZhiChunLu'), (175, 'WuDaoKou'), (176, 'YuanMingYuan'),
                                       (177, 'MuDanYuan'),
                                       (178, 'XiBeiWang'), (179, 'XueYuanLu'),
                                       (180, 'WanLiu'), (181, 'ZhongGuanCun'), (182, 'XiErQi'), (183, 'YangZhuang'),
                                       (184, 'WeiGongCun'), (185, 'ShiJiCheng'),
                                       (186, 'BaiShiQiao'),
                                       (187, 'BeiTaiPingZhuang'), (188, 'HaiDian Other'), (189, 'HuaiRou'),
                                       (190, 'DaYu'), (191, 'ShiMenYing'),
                                       (192, 'ChengZi'), (193, 'BinHeXiQu'),
                                       (194, 'FengCun'), (195, 'MenTouGou Other'), (196, 'MiYun Other'),
                                       (197, 'PingGu Other'), (198, 'LuGu'),
                                       (199, 'BaJiao'), (200, 'PingGuoYuan'),
                                       (201, 'ShiJingShan Other'), (202, 'GuCheng'), (203, 'LaoShan'), (204, 'MaPo'),
                                       (205, 'ShunYi Other'),
                                       (206, 'ShunYiCheng'), (207, 'HouShaYu'),
                                       (208, 'TianZhu'), (209, 'LiQiao'), (210, 'QiaoZhuang'), (211, 'BeiGuan'),
                                       (212, 'WanDa'), (213, 'LinHeLi'),
                                       (214, 'WuYiHuanYuan'),
                                       (215, 'GuoYuan'), (216, 'YuQiao'), (217, 'LiYuan'), (218, 'JiuKeShu(JiaLeFu)'),
                                       (219, 'LuYuan'),
                                       (220, 'TongZhouBeiYuan'), (221, 'TongZhou Other'),
                                       (222, 'MaJuQiao'), (223, 'JinRongJie'), (224, 'NiuJie'), (225, 'YouAnMenNei'),
                                       (226, 'MuXiDi'),
                                       (227, 'XiDan'), (228, 'ChangChunJie'), (229, 'YueTan'),
                                       (230, 'CheGongZhuang'), (231, 'FuChengMen'), (232, 'TianNingSi'),
                                       (233, 'XuanWuMen'), (234, 'GuanYuan'),
                                       (235, 'BaiZhiFang'), (236, 'LiuPuKang'), (237, 'DeShengMen'),
                                       (238, 'XiSi'), (239, 'YanQing Other')],
                              coerce=int)
    search = SubmitField('Search')


class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')


class MessageForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(message=u'邮箱格式不正确'), Email()])
    phone = StringField('Phone Number', validators=[DataRequired()])
    information = TextAreaField('Message Information', validators=[DataRequired()])
    submit = SubmitField('Send')
